name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    environment: development
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Submit Azure ML job
      run: az ml job create --file src/job.yml --resource-group ${{vars.RESOURCEGROUP_NAME}} --workspace-name ${{vars.WORKSPACE_NAME}} --name diabetes-job-github-manual-action --set inputs.training_data.path=${{vars.TRAININGDATA_PATH}} compute=${{vars.COMPUTECLUSTER_NAME}}


