name: Automated modelt training for dev and prod data

on:
  pull_request:
    branches: [ main ]

jobs:
  job1:
    name: train model on dev data
    environment: development
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Submit Azure ML job
      run: az ml job create --file src/job.yml --resource-group ${{vars.RESOURCEGROUP_NAME}} --workspace-name ${{vars.WORKSPACE_NAME}} --set inputs.training_data.path=${{vars.TRAININGDATA_PATH}} inputs.compute=${{vars.COMPUTECLUSTER_NAME}}   --name diabetes-job-github-action

  job2:
    needs: job1
    name: train model on prod data
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Submit Azure ML job
      run: az ml job create --file src/job.yml --resource-group ${{vars.RESOURCEGROUP_NAME}} --workspace-name ${{vars.WORKSPACE_NAME}} --set inputs.training_data.path=${{vars.TRAININGDATA_PATH}} inputs.compute=${{vars.COMPUTECLUSTER_NAME}}   --name diabetes-job-github-action-prod