name: Manually deploy model to endpoint

on:
  workflow_dispatch:

jobs:
  deployModelToEndpoint:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Deploy online endpoint
      run: az ml online-endpoint create --name diabetesMlflowEndpoint -f production/endpoints/endpoint.yml --resource-group ${{vars.RESOURCEGROUP_NAME}} --workspace-name ${{vars.WORKSPACE_NAME}}
    - name: Deploy model to endpoint
      run: az ml online-deployment create --name diabetesMlflowDeployment --endpoint-name diabetesMlflowEndpoint -f production/endpoints/deployment.yml  --resource-group ${{vars.RESOURCEGROUP_NAME}} --workspace-name ${{vars.WORKSPACE_NAME}} --all-traffic
    

